distritos_pty = ["san felipe", "el chorrillo", "santa ana", "calidonia", "curundú", "betania", "bella vista", 
"pueblo nuevo", "san francisco", "parque lefevre", "río abajo", "juan díaz", "pedregal", "ancón", "chilibre", 
"las cumbres", "pacora", "san martín", "tocumen", "las mañanitas", "24 de diciembre", "alcalde díaz", 
"ernesto córdoba campos"]

pizzerias_por_distrito = [
    ["san felipe", "Basilico Pizzeria Italiano", "Calle 8 Este"],
    ["san felipe", "Barrio Pizza", "Avenida Central, Local 1"],  
    ["las cumbres", "Pizzería Giovanni's", "Cerca del Templo Hare Krishna"],  
    ["las cumbres", "Pizzería Las Cumbres", "Vía Transístmica, Plaza Las Cumbres"],
    ["el chorrillo", "Pizzería El Chorrillo", "Calle 16 Oeste, Edificio 5"],
    ["el chorrillo", "Pizza Express", "Avenida A, frente al Parque de Los Aburridos"],
    ["santa ana", "Pizzería Santa Ana", "Calle 13 Oeste, Edificio 10"],
    ["santa ana", "La Rústica", "Avenida Central, frente a la Plaza Santa Ana"],
    ["calidonia", "Pizzería Calidonia", "Vía España, Edificio 30"],
    ["calidonia", "Pizza al Paso", "Avenida Perú, cerca de la Estación del Metro"],
    ["curundú", "Pizzería Curundú", "Calle Principal, Edificio 12"],
    ["curundú", "Pizza Rápida", "Avenida Nacional, frente al Mercado de Abastos"],
    ["betania", "Pizzería Betania", "Calle 74 Oeste, Plaza Betania"],
    ["betania", "Pizza Gourmet", "Avenida Ricardo J. Alfaro, Plaza Edison"],
    ["bella vista", "Pizzería Bella Vista", "Calle 42 Este, Edificio 15"],
    ["bella vista", "La Pizzería", "Avenida Balboa, frente al Parque Urracá"],
    ["pueblo nuevo", "Pizzería Pueblo Nuevo", "Calle 6ta, Edificio 8"],
    ["pueblo nuevo", "Pizza & Más", "Avenida 12 de Octubre, Plaza Pueblo Nuevo"],
    ["san francisco", "Pizzería San Francisco", "Calle 50, Plaza San Francisco"],
    ["san francisco", "Pizza Moderna", "Vía Porras, Edificio 22"],
    ["parque lefevre", "Pizzería Parque Lefevre", "Calle 2da, Edificio 18"],
    ["parque lefevre", "Pizza al Gusto", "Avenida Ernesto T. Lefevre, Plaza Lefevre"],
    ["río abajo", "Pizzería Río Abajo", "Calle 13, Edificio 7"],
    ["río abajo", "Pizza del Río", "Vía España, frente a la Iglesia de Fátima"],
    ["juan díaz", "Pizzería Juan Díaz", "Calle Principal, Plaza Juan Díaz"],
    ["juan díaz", "Pizza & Sabor", "Avenida José Agustín Arango, Centro Comercial Los Pueblos"],
    ["pedregal", "Pizzería Pedregal", "Calle 9na, Edificio 3"],
    ["pedregal", "Pizza Express", "Vía Tocumen, Plaza Pedregal"],
    ["ancón", "Pizzería Ancón", "Calle Quarry Heights, Edificio 5"],
    ["ancón", "Pizza Colonial", "Avenida Omar Torrijos, cerca del Edificio de la Administración del Canal"],
    ["chilibre", "Pizzería Chilibre", "Calle Principal, Plaza Chilibre"],
    ["chilibre", "Pizza del Norte", "Transístmica, frente a la Estación de Policía"],
    ["pacora", "Pizzería Pacora", "Calle 5ta, Edificio 2"],
    ["pacora", "Pizza Campestre", "Vía Panamericana, Plaza Pacora"],
    ["san martín", "Pizzería San Martín", "Calle Central, Edificio 1"],
    ["san martín", "Pizza Rural", "Carretera Panamericana, frente al Parque San Martín"],
    ["tocumen", "Pizzería Tocumen", "Calle 2da, Edificio 9"],
    ["tocumen", "Pizza Aérea", "Avenida Domingo Díaz, Plaza Tocumen"],
    ["las mañanitas", "Pizzería Las Mañanitas", "Calle 4ta, Edificio 6"],
    ["las mañanitas", "Pizza del Este", "Vía Tocumen, Centro Comercial Las Mañanitas"],
    ["24 de diciembre", "Pizzería 24 de Diciembre", "Calle 8va, Edificio 11"],
    ["24 de diciembre", "Pizza del Sol", "Avenida Panamericana, Plaza 24 de Diciembre"],
    ["alcalde díaz", "Pizzería Alcalde Díaz", "Calle Principal, Edificio 4"],
    ["alcalde díaz", "Pizza Serrana", "Vía Transístmica, Plaza Alcalde Díaz"],
    ["ernesto córdoba campos", "Pizzería Ernesto Córdoba", "Calle 10, Edificio 7"],
    ["ernesto córdoba campos", "Pizza Urbana", "Avenida Simón Bolívar, Plaza Ernesto Córdoba"]
]


